spring:
    datasource:
        url: jdbc:h2:mem:testdb
        username: i
        password:
        driver-class-name: org.h2.Driver
        platform: h2
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true



